# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#f63366"
backgroundColor="#2a2a2a"
secondaryBackgroundColor="#333333"
textColor="#ffffff"
font="sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

# This hides the hamburger menu (and prevents opening it with "H")
[deprecation]
showMenu = false
